// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Railway_Management.Procesures;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Railway_Management.Procesures
{
    public partial interface IRailwayManagementContextProcedures
    {
        Task<List<UpdateCustomerImageResult>> UpdateCustomerImageAsync(int? customerID, string imageURL, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
