// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Railway_Management.Procesures;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Railway_Management.Procesures
{
    public partial class RailwayManagementContext
    {
        private IRailwayManagementContextProcedures _procedures;

        public virtual IRailwayManagementContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RailwayManagementContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRailwayManagementContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class RailwayManagementContextProcedures : IRailwayManagementContextProcedures
    {
        private readonly RailwayManagementContext _context;

        public RailwayManagementContextProcedures(RailwayManagementContext context)
        {
            _context = context;
        }

        public virtual async Task<List<UpdateCustomerImageResult>> UpdateCustomerImageAsync(int? customerID, string imageURL, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "CustomerID",
                    Value = customerID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ImageURL",
                    Size = 255,
                    Value = imageURL ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UpdateCustomerImageResult>("EXEC @returnValue = [dbo].[UpdateCustomerImage] @CustomerID = @CustomerID, @ImageURL = @ImageURL", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
