// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Railway_Management.Procesures
{
    public partial class UpdateCustomerImageResult
    {
        public int Result { get; set; }
    }
}
